[package]
name = "template-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.13", features = ["json"] }
tokio = { version = "1.24.1", features = ["full"]}
serde = { version = "1.0.152", features = ["derive"]}
serde_json = "1.0.91"
async-recursion = "1.0.0"